name: CI-CD pipeline workflow

#trigger
on:
    push:
        branches:
        - main

#defines jobs
jobs:
    test-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v6
              with:
                python-version: "3.10"

            - name: install dependencies
              run: pip install -r .github\workflows\requirements.txt

            - name: run test case
              run: pytest --cov=calc --cov-report=term
            

    deploy-job:
        runs-on: ubuntu-latest
        needs: test-jobs
        steps:
            - name: print message
              run: echo "deploy job started"
